Owl\Component\Notification\Model\Notification:
    exclusion_policy: ALL
    xml_root_name: notification
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [AjaxShow, Autocomplete]
        subject:
            expose: true
            type: string
            groups: [AjaxShow, Autocomplete]
